HunyuanImage3Config_dict = {
  "add_classification_head": False,
  "anyres_pooling_size": 2,
  "anyres_vit_max_image_size": None,
  "anyres_vit_two_views": False,
  "architectures": [
    "HunyuanImage3ForCausalMM"
  ],
  "attention_bias": False,
  "attention_dropout": 0.0,
  "attention_head_dim": 128,
  "auto_map": {
    "AutoConfig": "configuration_hunyuan.HunyuanImage3Config",
    "AutoModel": "hunyuan.HunyuanImage3Model",
    "AutoModelForCausalLM": "hunyuan.HunyuanImage3ForCausalMM"
  },
  "bos_token_id": 127958,
  "capacity_factor": 1.0,
  "cla_share_factor": 2,
  "class_num": 0,
  "dense_list": [
    4096,
    0
  ],
  "dtype": "bfloat16",
  "eod_token_id": 3,
  "eos_token_id": 127957,
  "group_limited_greedy": False,
  "head_dim": 128,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "im_end_id": 128001,
  "im_newline_id": 11,
  "im_start_id": 128000,
  "image_base_size": 1024,
  "image_token_id": 128006,
  "img_proj_type": "unet",
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "kv_lora_rank": None,
  "mask_init_id": 12,
  "max_position_embeddings": 12800,
  "mlp_bias": False,
  "model_type": "Hunyuan",
  "moe_drop_tokens": False,
  "moe_impl": "eager",
  "moe_intermediate_size": [
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072,
    3072
  ],
  "moe_layer_num_skipped": 0,
  "moe_random_routing_dropped_token": False,
  "moe_topk": [
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8,
    8
  ],
  "n_group": False,
  "norm_topk_prob": True,
  "norm_type": "rms",
  "num_attention_heads": 32,
  "num_experts": 64,
  "num_hidden_layers": 32,
  "num_key_value_heads": 8,
  "num_media_embeds": 257,
  "num_shared_expert": [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1
  ],
  "pad_id": 128009,
  "pad_token_id": 128009,
  "patch_embed_hidden_dim": 1024,
  "patch_size": 1,
  "pool_type": "last",
  "position_embedding_xdrope": False,
  "pretraining_tp": 1,
  "q_lora_rank": None,
  "qk_nope_head_dim": None,
  "qk_rope_head_dim": None,
  "rms_norm_eps": 1e-05,
  "rope_scaling": {
    "alpha": 1.0,
    "beta_fast": 32,
    "beta_slow": 1,
    "factor": 1.0,
    "mscale": 1.0,
    "mscale_all_dim": 1.0,
    "type": "custom"
  },
  "rope_theta": 10000.0,
  "routed_scaling_factor": False,
  "skip_cls_token": False,
  "text_end_id": 7,
  "text_start_id": 6,
  "tie_word_embeddings": False,
  "topk_group": False,
  "transformers_version": "4.57.3",
  "use_cache": True,
  "use_cla": False,
  "use_mixed_mlp_moe": True,
  "use_mla": False,
  "use_qk_norm": True,
  "use_rotary_pos_emb": True,
  "v_head_dim": None,
  "vae": {
    "_class_name": "AutoencoderKLConv3D",
    "block_out_channels": [
      128,
      256,
      512,
      1024,
      1024
    ],
    "downsample_match_channel": True,
    "ffactor_spatial": 16,
    "ffactor_temporal": 4,
    "in_channels": 3,
    "latent_channels": 32,
    "layers_per_block": 2,
    "out_channels": 3,
    "sample_size": 384,
    "sample_tsize": 96,
    "scaling_factor": 0.562679178327931,
    "upsample_match_channel": True
  },
  "vae_downsample_factor": [
    16,
    16
  ],
  "video_end_id": 10,
  "video_start_id": 9,
  "vit": {
    "_attn_implementation": "sdpa",
    "attention_dropout": 0.0,
    "hidden_act": "gelu_pytorch_tanh",
    "hidden_size": 1152,
    "intermediate_size": 4304,
    "layer_norm_eps": 1e-06,
    "num_attention_heads": 16,
    "num_channels": 3,
    "num_hidden_layers": 27,
    "num_patches": 256,
    "output_attentions": False,
    "output_hidden_states": False,
    "patch_size": 16,
    "torch_dtype": "float32",
    "use_return_dict": True
  },
  "vit_add_patchemb_bias": False,
  "vit_aligner": {
    "depth": 2,
    "input_dim": 1152,
    "n_embed": 4096,
    "projector_type": "mlp_gelu",
    "torch_dtype": "float32"
  },
  "vit_input_resolution": 224,
  "vit_mapping_type": "resampler",
  "vit_norm_type": "fused",
  "vit_patch": 1,
  "vit_path": None,
  "vit_processor": {
    "do_convert_rgb": None,
    "do_normalize": True,
    "do_rescale": True,
    "do_resize": True,
    "image_mean": [
      0.5,
      0.5,
      0.5
    ],
    "image_processor_type": "Siglip2ImageProcessorFast",
    "image_std": [
      0.5,
      0.5,
      0.5
    ],
    "max_num_patches": 1024,
    "patch_size": 16,
    "processor_class": "Siglip2Processor",
    "resample": 2,
    "rescale_factor": 0.00392156862745098
  },
  "vit_remove_prenorm": False,
  "vit_token": 64,
  "vit_type": None,
  "vit_used_rms_norm": False,
  "vocab_size": 133120,
  "xdrope_section": None
}
#config: HunyuanImage3Config
#HunyuanImage-3.0/hunyuan_image_3/configuration_hunyuan.py
#class HunyuanImage3Config(PretrainedConfig)